// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xaftgheqctktlnfqlzjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZnRnaGVxY3RrdGxuZnFsempnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NzY1NjAsImV4cCI6MjA1MzM1MjU2MH0.BnFlYQxiKCgycVUMoUHIi7YMzcMJ4yEhyjNJB0gDL64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);